# Generated by Django 5.2.7 on 2025-10-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('overdue', 'Overdue')], default='normal', max_length=10),
        ),
    ]
