# Generated by Django 5.2.7 on 2025-10-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='functionality_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interactivity_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='navigation_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='structure_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='style_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
